version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s -w -X github.com/Jawkx/ctxcat/internal/cmd.version={{.Version}} -X github.com/Jawkx/ctxcat/internal/cmd.commit={{.Commit}} -X github.com/Jawkx/ctxcat/internal/cmd.date={{.Date}}

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).

after:
  hooks:
    # This hook runs after the GitHub release is created.
    # It changes into the 'npm' directory, updates the version
    # in package.json to match the git tag, and publishes to npm.
    - cmd: >
        sh -c 'echo "Publishing version {{.Version}} to npm..." &&
        cd npm &&
        npm version {{.Version}} --no-git-tag-version &&
        npm publish --access public'
      dir: '{{ .Dir }}'
